/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;

/**
 *
 * @author trabajo
 */
public class FormularioVehiculos extends javax.swing.JFrame {

    int ejeX, ejeY ; //funcionalidad barra superior 
    Color myWhite= new Color(3, 5, 6);
    
    PanelIngresoV PIngreso   = new PanelIngresoV();
    PanelEliminar PEliminar  = new PanelEliminar();
    PanelSalida   PSalida    = new PanelSalida  ();
    
    //COLORES SELECCION OPCIONES
    Color colDormido = new Color(51,52,78);
    Color colDespierto = new Color(39,38,60);
    
    public FormularioVehiculos() {
        initComponents();
        
//        PnlIngreso.setLocation(0,0);
//        ContenedorPanel.removeAll();
//        ContenedorPanel.add(PnlIngreso);
//        ContenedorPanel.revalidate();
//        ContenedorPanel.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        backGroundMenu = new javax.swing.JPanel();
        IngresarPanel = new javax.swing.JPanel();
        Ingresar = new javax.swing.JTextField();
        RetirarPanel = new javax.swing.JPanel();
        Retirar = new javax.swing.JTextField();
        EliminarPanel = new javax.swing.JPanel();
        Eliminar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ContenedorPanel = new javax.swing.JPanel();
        carro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JPanel();
        ExitT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundMenu.setBackground(new java.awt.Color(51, 52, 78));
        backGroundMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresarPanel.setBackground(new java.awt.Color(51, 52, 78));
        IngresarPanel.setForeground(new java.awt.Color(51, 52, 78));

        Ingresar.setEditable(false);
        Ingresar.setBackground(new java.awt.Color(51, 52, 78));
        Ingresar.setFont(new java.awt.Font("Roboto Thin", 1, 16)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(241, 239, 241));
        Ingresar.setText("    Ingresar");
        Ingresar.setBorder(null);
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IngresarPanelLayout = new javax.swing.GroupLayout(IngresarPanel);
        IngresarPanel.setLayout(IngresarPanelLayout);
        IngresarPanelLayout.setHorizontalGroup(
            IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IngresarPanelLayout.setVerticalGroup(
            IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backGroundMenu.add(IngresarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, -1));

        RetirarPanel.setBackground(new java.awt.Color(51, 52, 78));

        Retirar.setEditable(false);
        Retirar.setBackground(new java.awt.Color(51, 52, 78));
        Retirar.setFont(new java.awt.Font("Roboto Thin", 1, 16)); // NOI18N
        Retirar.setForeground(new java.awt.Color(241, 239, 241));
        Retirar.setText("    Retirar");
        Retirar.setToolTipText("");
        Retirar.setBorder(null);
        Retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetirarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RetirarMouseExited(evt);
            }
        });
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RetirarPanelLayout = new javax.swing.GroupLayout(RetirarPanel);
        RetirarPanel.setLayout(RetirarPanelLayout);
        RetirarPanelLayout.setHorizontalGroup(
            RetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetirarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RetirarPanelLayout.setVerticalGroup(
            RetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetirarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backGroundMenu.add(RetirarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 37));

        EliminarPanel.setBackground(new java.awt.Color(51, 52, 78));

        Eliminar.setEditable(false);
        Eliminar.setBackground(new java.awt.Color(51, 52, 78));
        Eliminar.setFont(new java.awt.Font("Roboto Thin", 1, 16)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(241, 239, 241));
        Eliminar.setText("    Eliminar");
        Eliminar.setBorder(null);
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarMouseExited(evt);
            }
        });
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarPanelLayout = new javax.swing.GroupLayout(EliminarPanel);
        EliminarPanel.setLayout(EliminarPanelLayout);
        EliminarPanelLayout.setHorizontalGroup(
            EliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EliminarPanelLayout.setVerticalGroup(
            EliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backGroundMenu.add(EliminarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Trabajo.jpg"))); // NOI18N
        backGroundMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 70));

        BackGround.add(backGroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 310));

        ContenedorPanel.setBackground(new java.awt.Color(212, 212, 212));
        ContenedorPanel.setLayout(null);

        carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche.jpg"))); // NOI18N
        ContenedorPanel.add(carro);
        carro.setBounds(150, 60, 250, 180);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Julian Esteban Quintero & Luis Fernando Martinez");
        ContenedorPanel.add(jLabel4);
        jLabel4.setBounds(110, 260, 330, 30);

        BackGround.add(ContenedorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 560, 310));

        BarraSuperior.setBackground(new java.awt.Color(39, 38, 60));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 239, 241));

        ExitBtn.setBackground(new java.awt.Color(241, 239, 241));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });

        ExitT.setBackground(new java.awt.Color(241, 239, 241));
        ExitT.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        ExitT.setForeground(new java.awt.Color(39, 38, 60));
        ExitT.setText(" X");

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ExitT, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ExitT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("   Automatic Mode");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 239, 241));
        jLabel3.setText("    Par King");

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BackGround.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerPaneles(JPanel p){
        p.setLocation(10,10);
        p.setSize(540, 295);
        ContenedorPanel.removeAll();
        ContenedorPanel.add(p);
        ContenedorPanel.revalidate();
        ContenedorPanel.repaint();
    }
    
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetirarActionPerformed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
        // TODO add your handling code here:
        ejeX = evt.getX(); // guarda la posicion en el eje x del mause
        ejeY = evt.getY(); // guarda la posicion en el eje y del mause
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - ejeX, y - ejeY);
        
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    
    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        // TODO add your handling code here:
        Color DarkVioleta = new Color(39,38,60);
        ExitT.setForeground(DarkVioleta);
    }//GEN-LAST:event_ExitBtnMouseExited

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        // TODO add your handling code here:
        ExitT.setForeground(Color.red);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void IngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseEntered
        // TODO add your handling code here:
        Ingresar.setFont(new Font("Roboto Thin", Font. BOLD, 18));
        
    }//GEN-LAST:event_IngresarMouseEntered

    private void IngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseExited
        // TODO add your handling code here:
        Ingresar.setFont(new Font("Roboto Thin", Font. BOLD, 16));
    }//GEN-LAST:event_IngresarMouseExited

    private void RetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseEntered
        // TODO add your handling code here:
        Retirar.setFont(new Font("Roboto Thin", Font. BOLD, 18));
    }//GEN-LAST:event_RetirarMouseEntered

    private void RetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseExited
        // TODO add your handling code here:
        Retirar.setFont(new Font("Roboto Thin", Font. BOLD, 16));
    }//GEN-LAST:event_RetirarMouseExited

    private void EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseEntered
        // TODO add your handling code here:
        Eliminar.setFont(new Font("Roboto Thin", Font. BOLD, 18));
    }//GEN-LAST:event_EliminarMouseEntered

    private void EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseExited
        // TODO add your handling code here:
        Eliminar.setFont(new Font("Roboto Thin", Font. BOLD, 16));
    }//GEN-LAST:event_EliminarMouseExited

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked
        // TODO add your handling code here:
        Ingresar.setBackground(colDespierto);
        Retirar.setBackground(colDormido);
        Eliminar.setBackground(colDormido);
        
        VerPaneles(PIngreso);
    }//GEN-LAST:event_IngresarMouseClicked

    private void RetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseClicked
        // TODO add your handling code here:
        Ingresar.setBackground(colDormido);
        Retirar.setBackground(colDespierto);
        Eliminar.setBackground(colDormido);
        
        VerPaneles(PSalida);
    }//GEN-LAST:event_RetirarMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        Ingresar.setBackground(colDormido);
        Retirar.setBackground(colDormido);
        Eliminar.setBackground(colDespierto);
        
        VerPaneles(PEliminar);
    }//GEN-LAST:event_EliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel ContenedorPanel;
    public javax.swing.JTextField Eliminar;
    private javax.swing.JPanel EliminarPanel;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitT;
    public javax.swing.JTextField Ingresar;
    private javax.swing.JPanel IngresarPanel;
    public javax.swing.JTextField Retirar;
    private javax.swing.JPanel RetirarPanel;
    private javax.swing.JPanel backGroundMenu;
    private javax.swing.JLabel carro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
